// <auto-generated />
using System;
using EduTrack.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTrack.API.Migrations
{
    [DbContext(typeof(EduTrackDbContext))]
    partial class EduTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduTrack.API.Models.DiemSo", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<decimal?>("Diem15p")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemMieng")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemTBMon")
                        .HasColumnType("decimal(4,2)");

                    b.Property<byte>("HocKy")
                        .HasColumnType("tinyint");

                    b.Property<string>("MaHS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaHS", "MaMon", "HocKy")
                        .IsUnique();

                    b.ToTable("DiemSos");
                });

            modelBuilder.Entity("EduTrack.API.Models.GiaoVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaGV");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("EduTrack.API.Models.HocPhi", b =>
                {
                    b.Property<int>("MaHocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocPhi"));

                    b.Property<byte>("HocKy")
                        .HasColumnType("tinyint");

                    b.Property<string>("MaHS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayDong")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHocPhi");

                    b.HasIndex("MaHS");

                    b.ToTable("HocPhis");
                });

            modelBuilder.Entity("EduTrack.API.Models.HocSinh", b =>
                {
                    b.Property<string>("MaHS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email_PhuHuynh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT_PhuHuynh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHS");

                    b.HasIndex("MaLop");

                    b.ToTable("HocSinhs");
                });

            modelBuilder.Entity("EduTrack.API.Models.LichHoc", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<string>("MaGV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("Thu")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TietBD")
                        .HasColumnType("int");

                    b.Property<int?>("TietKT")
                        .HasColumnType("int");

                    b.HasKey("MaLich");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMon");

                    b.ToTable("LichHocs");
                });

            modelBuilder.Entity("EduTrack.API.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KhoiLop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaGVChuNhiem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGVChuNhiem");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("EduTrack.API.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("HeSoThi")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("MaGV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaGV");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("EduTrack.API.Models.ThongBao", b =>
                {
                    b.Property<int>("MaTB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTB"));

                    b.Property<string>("LoaiTB")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaTB");

                    b.HasIndex("MaHS");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("EduTrack.API.Models.DiemSo", b =>
                {
                    b.HasOne("EduTrack.API.Models.HocSinh", "HocSinh")
                        .WithMany("DiemSos")
                        .HasForeignKey("MaHS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrack.API.Models.MonHoc", "MonHoc")
                        .WithMany("DiemSos")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("EduTrack.API.Models.HocPhi", b =>
                {
                    b.HasOne("EduTrack.API.Models.HocSinh", "HocSinh")
                        .WithMany("HocPhis")
                        .HasForeignKey("MaHS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("EduTrack.API.Models.HocSinh", b =>
                {
                    b.HasOne("EduTrack.API.Models.LopHoc", "LopHoc")
                        .WithMany("HocSinhs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("EduTrack.API.Models.LichHoc", b =>
                {
                    b.HasOne("EduTrack.API.Models.GiaoVien", "GiaoVien")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EduTrack.API.Models.LopHoc", "LopHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrack.API.Models.MonHoc", "MonHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("EduTrack.API.Models.LopHoc", b =>
                {
                    b.HasOne("EduTrack.API.Models.GiaoVien", "GiaoVienChuNhiem")
                        .WithMany("LopChuNhiems")
                        .HasForeignKey("MaGVChuNhiem")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GiaoVienChuNhiem");
                });

            modelBuilder.Entity("EduTrack.API.Models.MonHoc", b =>
                {
                    b.HasOne("EduTrack.API.Models.GiaoVien", "GiaoVien")
                        .WithMany("MonHocs")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("EduTrack.API.Models.ThongBao", b =>
                {
                    b.HasOne("EduTrack.API.Models.HocSinh", "HocSinh")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaHS")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("EduTrack.API.Models.GiaoVien", b =>
                {
                    b.Navigation("LichHocs");

                    b.Navigation("LopChuNhiems");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("EduTrack.API.Models.HocSinh", b =>
                {
                    b.Navigation("DiemSos");

                    b.Navigation("HocPhis");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("EduTrack.API.Models.LopHoc", b =>
                {
                    b.Navigation("HocSinhs");

                    b.Navigation("LichHocs");
                });

            modelBuilder.Entity("EduTrack.API.Models.MonHoc", b =>
                {
                    b.Navigation("DiemSos");

                    b.Navigation("LichHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
